### ISSUE TITLE
Non-existing translations (core)

### ISSUE THREAD

**Issue by iPurpl3x** [qiaeru/lang-french#30]
These translations that this pack provides only exist here, not in EN.

- core.forum.edit_user.activate_button
- core.forum.edit_user.groups_heading
- core.forum.edit_user.nothing_available
- core.forum.edit_user.set_password_label
- core.forum.edit_user.title

I guess they have been moved to another namespace.

**Comment by iPurpl3x** [comment]
There is actually more, the list is too long. Just use FoF Linguist to see what has no original translation in EN.

**Comment by qiaeru** [comment]
Yes you're right, but that's because I use an instance of [Weblate](https://weblate.rob006.net/languages/fr/flarum/) which keeps some old language keys. They will be removed in the future, but note there's is no impact for your forum (it doesn't loads these unused keys), only some bytes in your hosting. 🙂

**Comment by iPurpl3x** [comment]
@qiaeru Yes I know that there is no impact. It's just that I saw them and thought that it would be good to let you know.

**Comment by qiaeru** [comment]
Thank you for that. 👍
